#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
src_dir="${dir}/.."
source "${src_dir}/util"
util_setup "$dir"

task=''
set +u; db="$db_uri"; set -u

usage(){ echo "Usage: iris-daily: ${0} [--task <morning|night|all...>]" 1>&2; exit 1; }
while [[ $# -gt 0 ]]; do
  case "$1" in
    -t|--task)  task="$2"; shift ;;
    --testing)  task='testing' ;;
  esac
  shift
done
if [[ -z $task ]]; then usage; fi

daily(){
  if [[ -n $db ]]; then
    _report_athena portfolio 'skilbjo' "$email"
  else
    _report        portfolio 'skilbjo' "$email"
    _report        portfolio 'michie'  "$michie"
  fi
}

testing(){
  if [[ ! -z $db ]]; then
    _report        portfolio 'skilbjo' "$email"
  else
    _report_athena portfolio 'skilbjo' "$email"
  fi
}

case "$task" in
  daily )   daily && \
              ping_healthchecks "$healthchecks_io_iris";;
  testing ) testing ;;
  * ) echo 'in src/run-it, no args provided' && exit 1 ;;
esac
