#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
app_name=$(basename $(dirname $dir))

# db
  #-e db_uri="$(echo $db_uri)" \
  #-e db_uri="$(echo 'postgres://postgres@192.168.99.100:5432/postgres')" \

run_container(){
  docker run -it --rm \
    --name="$(echo $app_name)" \
    -e aws_access_key_id="$(cat ~/.aws/credentials | grep -A 2 skilbjo-robot | grep aws_access_key_id | awk '{print $3}')" \
    -e aws_secret_access_key="$(cat ~/.aws/credentials | grep -A 2 skilbjo-robot | grep aws_secret_access_key | awk '{print $3}')" \
    -e _email="$(echo $email)" \
    -e email_pw="$(echo $email_pw)" \
    -e healthchecks_io_iris="$(echo $healthchecks_io_iris)" \
    "$app_name":dev bash
}

run_arm(){
  local image_tag='arm_dev'

  docker run -it --rm \
    --name="$(echo $app_name)" \
    -e aws_access_key_id="$(cat ~/.aws/credentials | grep -A 2 skilbjo-robot | grep aws_access_key_id | awk '{print $3}')" \
    -e aws_secret_access_key="$(cat ~/.aws/credentials | grep -A 2 skilbjo-robot | grep aws_secret_access_key | awk '{print $3}')" \
    -e _email="$(echo $email)" \
    -e email_pw="$(echo $email_pw)" \
    -e healthchecks_io_iris="$(echo $healthchecks_io_iris)" \
    "${app_name}:${image_tag}" bash
}

run_debian(){
  local image_tag='x86-debian_dev'

  docker run -it --rm \
    --name="$(echo $app_name)" \
    -e aws_access_key_id="$(cat ~/.aws/credentials | grep -A 2 skilbjo-robot | grep aws_access_key_id | awk '{print $3}')" \
    -e aws_secret_access_key="$(cat ~/.aws/credentials | grep -A 2 skilbjo-robot | grep aws_secret_access_key | awk '{print $3}')" \
    -e _email="$(echo $email)" \
    -e email_pw="$(echo $email_pw)" \
    -e healthchecks_io_iris="$(echo $healthchecks_io_iris)" \
    "${app_name}:${image_tag}" bash
}

run_minidock(){
  local image_tag='x86-debian-minicon_dev'

  if [[ $(cat /etc/os-release | grep 'Linux') == 'Linux' ]] && [[ -f /etc/os-release ]]; then
    source "./util"
    get_udocker
  else
    echo 'Not running in Linux. Try again inside a Debian VM.' 2>&1 && exit 1
  fi

  /tmp/udocker pull "${app}:${image_tag}"
  /tmp/udocker create --name="$app" "${app}:${image_tag}"
  /tmp/udocker setup --execmode=F1 "$app"

  /tmp/udocker run --nosysdirs \
    -v /dev -v /proc -v /etc/hosts \
    --env="_email=${email}" \
    --env="email_pw=${email_pw}" \
    --env="aws_access_key_id=${aws_access_key_id}" \
    --env="aws_secret_access_key=${aws_secret_access_key}" \
    _ /bin/bash -c '/usr/local/deploy/bin/run-job'
}

run_container

#run_debian

# this can only be run on a Linux machine
#run_minidock
#run_arm
