#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
app_name=$(basename $(dirname $dir))

# aws
  #-e aws_access_key_id="$(echo '')" \
  #-e aws_secret_access_key="$(echo '')" \
# db
  #-e db_uri="$(echo $db_uri)" \

docker run -it --rm \
  --name="$(echo $app_name)" \
  -e db_uri="$(echo $db_uri)" \
  -e _email="$(echo $email)" \
  -e email_pw="$(echo $email_pw)" \
  "$app_name":dev bash
