#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
app_name=$(basename $(dirname $dir))

docker run -it --rm \
  -e db_uri="$(echo $db_uri)" \
  -e email="$(echo $email)" \
  "$app_name":dev bash
