#!/usr/bin/env bash
set -eou pipefail

email="$(echo "$email")"
distro_list="$(echo "$email")"
subject='test'
report='portfolio'
body="$(cat "${report}.html")"
attachment="$(gbase64 -w 0 "${report}.csv")"

msg="$(echo "From: ${email}
To: ${distro_list}
Subject: ${subject}
MIME-Version: 1.0
Content-Type: Multipart/Mixed; boundary=\"NextPart\"

--NextPart
Content-Type: text/html;

${body}

--NextPart
Content-Type: text/csv;
Content-Disposition: attachment; filename=${report}.csv
Content-Transfer-Encoding: base64

${attachment}

--NextPart--")"

jq -n --arg data "$msg" '{Data: $data}' >email.json

aws ses \
  send-raw-email \
  --profile personal \
  --region us-east-1 \
  --raw-message file://email.json

rm email.json
