#!/usr/bin/env bash
set -eou pipefail

resources_dir="usr/local/resources"
src_dir="usr/local/src"

setup(){
  export email="${_email}"

  source "${src_dir}/util"
  source "${src_dir}/athena"

  mkdir -p /out
}

_report(){
  report="$1"

  psql "$db_uri" --html -f "${resources_dir}/${report}.sql" >"/out/${report}"     # html
  psql "$db_uri" -AF',' -f "${resources_dir}/${report}.sql" >"/out/${report}.csv" # csv

  email $report
}

_portfolio(){
  exit_if weekend && exit_if holiday

  setup_email

  _report portfolio
}

_report_athena(){
  report="$1"

  query "$(cat ${resources_dir}/${report}_athena.sql)" >"/out/${report}.csv" # csv

  echo '<table border="2" cellspacing="1" cellpadding="2">'        >"/out/${report}"
  while read INPUT ; do
    echo "<tr><td align='center'>${INPUT//,/</td><td>}</td></tr>" >>"/out/${report}" ;
  done < "/out/${report}.csv" ;
  echo '</table>'                                                 >>"/out/${report}"

  email_aws $report
}

_portfolio_aws(){
  #exit_if weekend

  setup_aws

  _report_athena portfolio
}

setup \
  && set +u; if [[ ! -z $db_uri ]]; then _portfolio; else _portfolio_aws; fi; set -u
