#!/usr/bin/env bash
set -eou pipefail

setup_aws(){
  mkdir -p /root/.aws

  touch /root/.aws/config
  echo "[default]"           >/root/.aws/config
  echo "region = us-east-1" >>/root/.aws/config

  touch /root/.aws/credentials
  echo "[default]"                                       >/root/.aws/credentials
  echo "aws_access_key_id     = $aws_access_key_id"     >>/root/.aws/credentials
  echo "aws_secret_access_key = $aws_secret_access_key" >>/root/.aws/credentials

  export AWS_ACCESS_KEY_ID="$aws_access_key_id"
  export AWS_SECRET_ACCESS_KEY="$aws_secret_access_key"
}

setup_email(){
  echo set from = "${email}"                          >>/root/.muttrc \
    && echo set realname = "Iris"                     >>/root/.muttrc \
    && echo set imap_user = "${email}"                >>/root/.muttrc \
    && echo set imap_pass = "${email_pw}"             >>/root/.muttrc \
    && echo set folder = "imaps://imap.gmail.com:993" >>/root/.muttrc \
    && echo set spoolfile = "+INBOX"                  >>/root/.muttrc \
    && echo set postponed ="+[Gmail]/Drafts"          >>/root/.muttrc \
    && echo set header_cache =~/.mutt/cache/headers   >>/root/.muttrc \
    && echo set message_cachedir =~/.mutt/cache/bodies  >>/root/.muttrc \
    && echo set certificate_file =~/.mutt/certificates  >>/root/.muttrc \
    && echo set smtp_url = "smtps://$(echo $email | sed 's/@.*//')@smtp.gmail.com:465/"  >>/root/.muttrc \
    && echo set smtp_pass = "${email_pw}"             >>/root/.muttrc \
    && echo set move = no                             >>/root/.muttrc \
    && echo set imap_keepalive = 900                  >>/root/.muttrc \
    && echo set crypt_use_gpgme=no                    >>/root/.muttrc \
    && chown -R postfix /var/spool/postfix/ \
    && chown root /var/spool/postfix/ \
    && chown root /var/spool/postfix/pid \
    && postmap /etc/postfix/generic

  set +e
  postfix start || echo 'Postfix already running'
  set -e
  sleep 3
}

email_aws(){
  local report="$1"
  local subject="Iris report for ${report} on $(date -I)"
  local body="Iris report for $(date -I): $(cat "/out/${report}" | sed 's/\"//g' | tr -d "\n\r")"
  local attachment="$(base64 -w 0 /out/${report}.csv)"

  echo "{\"Data\": \"From: ${email}\\nTo: ${email}\\nSubject: ${subject}\\nMIME-Version: 1.0\\nContent-type: Multipart/Mixed; boundary=\\\"NextPart\\\"\\n\\n--NextPart\\nContent-Type: text/html;\\n\\n${body}\\n\\n--NextPart\\nContent-Type: text/csv;\\nContent-Disposition: attachment; filename=\\\"${report}.csv\\\"\\nContent-Transfer-Encoding: base64\\n\\n${attachment}\\n\\n--NextPart--\"}" >"/out/${report}.json"

  aws ses \
    send-raw-email \
    --region us-east-1 \
    --raw-message "file:///out/${report}.json"
}

email() {
  local report="$1"

  echo "Iris report for $(date -I): $(cat "/out/${report}")" | \
    mutt -e 'set content_type=text/html' \
      -s "Iris report for $report on $(date -I)" \
      -a "/out/${report}.csv" \
      -- $email
  sleep 5
}

exit_if(){
  case "$@" in
    weekend )
      case "$(date +%a)" in
        Sat | Sun)
          exit 0 ;; # silently exit - we don't care if not a weekday
        * )
          ;;
      esac
      ;;
    holiday )
      set +u
      if [[ ! -z $db_uri && "True" == $(psql $db_uri -tc 'select "official_public_holiday?" from dw.date_dim where date = now()::date;' | awk '{$1=$1};1' | head -n1) ]]; then
        exit 0
      fi
      set -u
      ;;
    *)
      ;;
  esac
}
