#!/usr/bin/env bash

ping_healthchecks(){
  job_uuid="$1"

  curl -fsS --retry 3 "https://hc-ping.com/${job_uuid}"
}

setup_aws(){
  if [[ $(whoami) == 'root' ]]; then
    local home_dir='/root'
  elif [[ $(whoami) == 'sbx_'* ]]; then
    local home_dir="/home/$(whoami)"
  elif [[ $(whoami) == 'skilbjo' ]]; then
    echo 'Easy, big guy...' && exit 1
  fi

  mkdir -p "${home_dir}/.aws"

  touch "${home_dir}/.aws/config"
  echo "[default]"           >"${home_dir}/.aws/config"
  echo "region = us-east-1" >>"${home_dir}/.aws/config"

  touch "${home_dir}/.aws/credentials"
  echo "[default]"                                       >"${home_dir}/.aws/credentials"
  echo "aws_access_key_id     = $aws_access_key_id"     >>"${home_dir}/.aws/credentials"
  echo "aws_secret_access_key = $aws_secret_access_key" >>"${home_dir}/.aws/credentials"

  export AWS_ACCESS_KEY_ID="$aws_access_key_id"
  export AWS_SECRET_ACCESS_KEY="$aws_secret_access_key"
}

setup_email(){
  if [[ $(whoami) == 'root' ]]; then
    local home_dir='/root'
  elif [[ $(whoami) == 'sbx_'* ]]; then
    local home_dir="/home/$(whoami)"
  elif [[ $(whoami) == 'skilbjo' ]]; then
    echo 'Easy, big guy...' && exit 1
  fi

  echo set from = "${email}"                           >>"${home_dir}/.muttrc" \
    && echo set realname = "Iris"                      >>"${home_dir}/.muttrc" \
    && echo set imap_user = "${email}"                 >>"${home_dir}/.muttrc" \
    && echo set imap_pass = "${email_pw}"              >>"${home_dir}/.muttrc" \
    && echo set folder = "imaps://imap.gmail.com:993"  >>"${home_dir}/.muttrc" \
    && echo set spoolfile = "+INBOX"                   >>"${home_dir}/.muttrc" \
    && echo set postponed ="+[Gmail]/Drafts"           >>"${home_dir}/.muttrc" \
    && echo set header_cache =~/.mutt/cache/headers    >>"${home_dir}/.muttrc" \
    && echo set message_cachedir =~/.mutt/cache/bodies >>"${home_dir}/.muttrc" \
    && echo set certificate_file =~/.mutt/certificates >>"${home_dir}/.muttrc" \
    && echo set smtp_url = "smtps://$(echo $email | sed 's/@.*//')@smtp.gmail.com:465/" >>"${home_dir}/.muttrc" \
    && echo set smtp_pass = "${email_pw}"              >>"${home_dir}/.muttrc" \
    && echo set smtp_authenticators = 'gssapi:login'   >>"${home_dir}/.muttrc" \
    && echo set move = no                              >>"${home_dir}/.muttrc" \
    && echo set imap_keepalive = 900                   >>"${home_dir}/.muttrc" \
    && echo set crypt_use_gpgme=no                     >>"${home_dir}/.muttrc" \
    && chown -R postfix /var/spool/postfix/ \
    && chown root /var/spool/postfix/ \
    && chown root /var/spool/postfix/pid \
    && postmap /etc/postfix/generic

  set +e
  postfix start || echo 'Postfix already running'
  set -e
  sleep 3
}

email_aws(){
  local report="$1"
  local distro_list="$2"
  local subject="Iris report for ${report} on $(date +%F)"
  local body="Iris report for $(date +%F): $(cat "${tmp_dir}/${report}.html" | sed 's/\"//g' | tr -d "\n\r")"
  if [[ $(whoami) == 'root' ]] || [[ $(whoami) == 'sbx_'* ]]; then
    local attachment="$(base64 -w 0 "${tmp_dir}/${report}.csv")"
  elif [[ $(whoami) == 'skilbjo' ]]; then
    local attachment="$(gbase64 -w 0 "${tmp_dir}/${report}.csv")"
  fi

  local msg="$(echo "From: ${email}
To: ${distro_list}
Subject: ${subject}
MIME-Version: 1.0
Content-Type: Multipart/Mixed; boundary=\"NextPart\"

--NextPart
Content-Type: text/html;

${body}

--NextPart
Content-Type: text/csv;
Content-Disposition: attachment; filename=${report}.csv
Content-Transfer-Encoding: base64

${attachment}

--NextPart--")"

jq -n --arg data "$msg" '{Data: $data}' >"/tmp/${report}.json"

  if [[ $(whoami) == 'root' ]]; then
    aws ses \
      send-raw-email \
      --region us-east-1 \
      --raw-message "file://${tmp_dir}/${report}.json"
  elif [[ $(whoami) == 'sbx_'* ]]; then
    set +e
    aws ses \
      send-raw-email \
      --region us-east-1 \
      --raw-message "file://${tmp_dir}/${report}.json"

    aws ses \
      send-raw-email \
      --region us-east-1 \
      --raw-message "fileb://${tmp_dir}/${report}.json"
    set -e
  elif [[ $(whoami) == 'skilbjo' ]]; then
    aws ses \
      send-raw-email \
      --profile personal \
      --region us-east-1 \
      --raw-message "file://${tmp_dir}/${report}.json"
  else
    >&2 echo "user is: $(whoami), add to setup fn"
  fi
}

email() {
  local report="$1"
  local distro_list="$2"

  echo "Iris report for $(date +%F): $(cat "/tmp/${report}")" | \
    mutt -e 'set content_type=text/html' \
      -s "Iris report for $report on $(date +%F)" \
      -a "/tmp/${report}.csv" \
      -- "$distro_list"
  sleep 3
}

csv_to_html(){
  local report="$1"

  echo '<table border="2" cellspacing="1" cellpadding="2">'         >"/tmp/${report}"
  local header='true'
  cat "/tmp/${report}.csv" | while read line; do
    if [[ $header == 'true' ]]; then
      echo "<tr><th align='center'>${line//,/</th><th>}</th></tr>" >>"/tmp/${report}";
      header='false';
    else
      echo "<tr><td align='center'>${line//,/</td><td>}</td></tr>" >>"/tmp/${report}";
    fi
  done
  echo '</table>'                                                  >>"/tmp/${report}"

  cat "/tmp/${report}"
}
